### ISSUE TITLE
Control-Shift-d not working

### ISSUE THREAD

**Issue by buhshanpjoshi** [tgandrews/atom-easy-jsdoc#4]
Hi I have installed the package in atom, but the shortcut is not working on windows.
Is anything missing? Please suggest

**Comment by tgandrews** [comment]
What versions of Windows, atom and the extension are you using?

**Comment by buhshanpjoshi** [comment]
Windows: Windows 7 Enterprise , 64 bit
Atom: 1.3.2

And what is the extension means?

**Comment by tgandrews** [comment]
Thanks for the info 👍

What version of the atom-easy-jsdoc are you using?

Also, do have any other packages installed as well?

**Comment by buhshanpjoshi** [comment]
atom-easy-jsdoc: 4.2.0 
I have atom-beautify and linter-eslint installed

**Comment by tgandrews** [comment]
I don't have a Windows machine to hand but I'll have a look when I do.

**Comment by tgandrews** [comment]
Thanks for the report 👍

**Comment by ebrightc** [comment]
I have installed Atom 1.3.2, atom-easy-jsdoc 4.2.0 and it looks like there is a key binding already in place for Control-Shift-D. Here is the snippet from the keybinding:

ctrl-shift-D	editor:duplicate-lines	Core	atom-workspace atom-text-editor:not([mini])
ctrl-shift-D	jsdoc:block	Atom Easy Jsdoc	atom-text-editor

**Comment by tgandrews** [comment]
Thanks. I'll have a play at a fix this weekend. Sounds like it needs to be
something else on Windows

**Comment by danactive** [comment]
BTW: I agree with @ebrightc Ctrl-Shift-D duplicates the line in Windows

**Comment by tgandrews** [comment]
What would be a preferred shortcut on Windows?

**Comment by ebrightc** [comment]
Control-shift-j doesnt seem to be taken by anything in core in mac or windows. There are so many key bindings that you have to take whats left.

**Comment by balessan** [comment]
Same thing on Ubuntu. Ctrl-Shift-D duplicating the current line.

**Comment by tgandrews** [comment]
Ok. I have a Windows laptop with the fix working. I will push it and
release it when I get home this evening.

Ctrl + shift + j good for everyone?

**Comment by balessan** [comment]
Good for me.

**Comment by ebrightc** [comment]
Sure. Thanks for being so responsive. I love the open source community!

**Comment by tgandrews** [comment]
Closed with commit 6763b47

**Comment by glandre** [comment]
What is the correct command on Mac Book? I installed here and tried: `Command+Shift+D`, `Control+Shift+D` and the same with `J` but nothing has worked...

**Comment by tgandrews** [comment]
@glandre as per docs `control+shift+j` on Mac. Please open a new issue if this doesn't work for you.

**Comment by glandre** [comment]
Hi @tgandrews, by reading the answers here I noticed that I should try to close Atom and reopened it. After doing that, both `control+shift+j` and `control+shift+d` worked. I'm sorry for the inconvenience.

**Comment by sansae** [comment]
Hi @tgandrews,
This is no longer an issue for me, but I just thought I'd share something I discovered in case others come across it later. (I'm not sure where else to put this)

Initially, ctrl+shift+j was not working for me either. I looked at the packages I had installed on atom, and it turns out the "Script" package, version 3.15.0, has the same key-binding of ctrl+shift+j, which performs a "Script: Run by Line Number" command.

As of 8/25/17, I can confirm that after disabling the "Script" package, ctrl+shift+j now works for generating a jsdoc comment.

My atom version is 1.19.3 ia32, and I have atom-easy-jsdoc, version 4.12.2

(side note: with Script pkg enabled and atom-easy-jsdoc disabled, ctrl+shift+j kept giving me this error:
"Line Number Based runner not available for JavaScript.
If it should exist, add an issue on GitHub, or send your own pull request.
^C")
